CREATE TABLE IF NOT EXISTS TELEMETRIA (
  ID_TELEMETRIA INT PRIMARY KEY AUTO_INCREMENT,
  DATA_REFERENCIA DATE NOT NULL,
  NOME_API VARCHAR(100),
  TEMPO_RESPOSTA_MS INT,
  STATUS_HTTP INT
);

CREATE TABLE IF NOT EXISTS SIMULACAO (
  ID_SIMULACAO INT PRIMARY KEY AUTO_INCREMENT,
  VALOR_DESEJADO DECIMAL(18,2) NOT NULL,
  PRAZO INT NOT NULL,
  CODIGO_PRODUTO INT NOT NULL,
  NOME_PRODUTO VARCHAR(200),
  TAXA_JUROS DECIMAL(10,9),
  VALOR_TOTAL_SAC DECIMAL(18,2),
  VALOR_TOTAL_PRICE DECIMAL(18,2),
  DATA_SIMULACAO TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PARCELA (
  ID_PARCELA INT PRIMARY KEY AUTO_INCREMENT,
  ID_SIMULACAO INT,
  TIPO VARCHAR(10),
  NUMERO INT,
  VALOR_AMORTIZACAO DECIMAL(18,2),
  VALOR_JUROS DECIMAL(18,2),
  VALOR_PRESTACAO DECIMAL(18,2),
  FOREIGN KEY (ID_SIMULACAO) REFERENCES SIMULACAO(ID_SIMULACAO)
);

-- Índices automáticos para H2 e SQL Server
CREATE INDEX IF NOT EXISTS IDX_Simulacao_DataProduto ON SIMULACAO (DATA_SIMULACAO, CODIGO_PRODUTO);
CREATE INDEX IF NOT EXISTS IDX_Telemetria_NomeApiData ON TELEMETRIA (NOME_API, DATA_REFERENCIA);
CREATE INDEX IF NOT EXISTS IDX_Telemetria_StatusHttp ON TELEMETRIA (STATUS_HTTP);
CREATE INDEX IF NOT EXISTS IDX_Simulacao_CodigoProduto ON SIMULACAO (CODIGO_PRODUTO);
